nephila/python-taiga

AUTHORS.txt, taiga/models/models.py, tests/test_milestones.py, tests/test_projects.py
First of all: wonderful project, I like working with python-taiga!
I want to fetch out some project stats but the stats API calls for Projects and Milestones were missing. I added these two calls and associated test cases with them.
API doc:
http://taigaio.github.io/taiga-doc/dist/api.html#projects-stats
http://taigaio.github.io/taiga-doc/dist/api.html#milestones-stats
=> Added stats for Projects and Milestones

taiga/models/models.py
The endpoint in the model for IssueType is set to 'issue-statuses' instead of 'issue-types'
=> Use correct endpoint for IssueType

.travis.yml, taiga/models/models.py, tests/test_projects.py
- Add project/<project_id>/issues_stats Api call
- Run tests in Python 3.5
- Prevent failures for timeouts during installing requirements in travis-ci (http://docs.travis-ci.com/user/build-timeouts/)
=> Minor improvements

runtests.sh
If there were not .coverage file when runtests.sh is invoked an error
message was printed out. This patch changes the test script so it tests
for the existence for the file before trying to remove it.
=> Only remove .coverage if it exists to avoid error message

taiga/models/models.py, tests/resources/milestone_details_success.json, tests/resources/milestones_list_success.json, tests/resources/search_success.json, tests/resources/userstories_list_success.json, tests/resources/userstory_details_success.json
I've had some problem using the is_archived boolean on User Stories
since the server did never return such a thing for User Stories. After
some email conversations with the Taiga developers it turns out that the
API documentation has been wrong for a while. The only thing that has an
'is_archived' attribute is the User Story Status detail object.
They have now updated the API docs with this. Therefore I remove the
is_archived attribute on US in this patch.
NOTE I've not been able to run the nosetests this time like I've been
able to do before. There were some problems installing the mock module
from PIP. Can some one else verify that this works? :)
=> Remove is_archived from User Story object

taiga/requestmaker.py
Changed header value of RequestMaker 'x-disable-pagination' header to be a string instead of boolean since the requests library enforces string (or binary) values for headers only and raises an exception since version 2.11.0.
=> Fix for broken RequestMaker when using requests>=2.11.0

setup.py
`python setup.py egg_info` can't find README.rst
fixes issue #45
=> Change README.rst to README.md

taiga/client.py, taiga/requestmaker.py, tests/test_requestmaker.py
Allow the connection to a Taiga host using a self-signed certificate (also ignore the InsecureWarning triggered by urllib3).
Taiga offers other types of authentication (LDAP, github, ...), so the key 'type' in the payload for the auth request can't be hard coded to 'normal'.
=> Unsecure login and auth_type

setup.py
Before, there was no link from [PyPi](https://pypi.python.org/pypi/python-taiga) page to the GitHub repository with the source. This is fixed by setting `url` in setup.py
=> Update setup.py to include URL to GitHub repository.

setup.py
The tests directory is currently being built as a separate module by setup.py. When python-taiga is installed, the tests are installed as a separate module (in /usr/local/lib/python2.7/dist-packages/tests) and can be imported using `import tests` (though the module is quite useless).
This change excludes the tests from the identified packages. Thus, it will no longer be installed.
=> Avoid installing tests as a separate module

taiga/models/base.py
This is needed as tox 3.0 changed the import order and dateutil is imported before the environment is ready
=> Move dateutil import

taiga/exceptions.py
Some exceptions cases does not provide a clear error message and we need to build a more meaningful one
=> Improve exception string representation

taiga/client.py, taiga/models/models.py, tests/resources/search_success.json, tests/test_search.py
* Add support for HIstory and Search
=> Improve epics support

.travis.yml, setup.py, tox.ini
Only travis and tox configuration changes was needed
=> Add support for python 3.7

changes/116.bugfix, taiga/models/base.py, tests/test_model_base.py, tests/test_user_stories.py
Page parameter was not passed to querystring, thus pagination failed
Ensure page parameter is actually passed to query parameters
Fix #116
=> Fix pagination

changes/114.bugfix, taiga/client.py, tests/resources/auth_user_success.json
Describe:
Updates tests/resources/auth_user_success.json file to add support for the `refresh` token
Adds support in `client.py` for the returned `refresh` token.
Fixes bug #114 
* tests `tox -e py3.9` and `inv lint` run locally
=> Fix for issue #114

changes/130.bugfix, taiga/models/base.py, taiga/models/models.py, tests/test_issue_statuses.py, tests/test_issue_types.py, tests/test_model_base.py, tests/test_points.py, tests/test_priorities.py, tests/test_severities.py, tests/test_task_statuses.py, tests/test_userstory_statuses.py
Add moveTo parameter to delete methods when needed by Taiga API
Fix #130
=> Add moveTo parameter to delete methods when needed by Taiga API

changes/131.feature, taiga/client.py, tests/resources/auth_refresh_token_success.json, tests/test_auth.py
Add refresh_token API call
Fix #131
=> Add refresh_token API call

changes/161.feature, docs/usage.rst, taiga/models/models.py, tests/test_projects.py
This PR adds a `duplicate()` method to the `Project` model, which will duplicate the project on Taiga when called.  This causes Taiga to make a new project using the newly specified name/description/is_private/users, but copying the original project's settings, including color names, priorities, etc.  It does not duplicate any user stories or tasks.
Fix #161
=> feature/161 - Add duplicate() method to Project (#161)

changes/166.feature, taiga/models/models.py, tests/resources/project_details_success.json
Adds support for reading/writing `default_swimlane` in `Project`.  Like any other property, you can read it:
```python
print(project.default_swimlane)
```
or update it:
```python
project.default_swimlane = 5
project.update()
```
Fixes #166 
Note I did not add any tests specifically, but did add the `default_swimlane` property to one of the resource JSONs.  As far as I can see, there are not tests to see if various parameters are returned when a GET happens.  Similarly, there were not docs on reading individual attributes so I did not update those.
=> Allow reading/writing default_swimlane in Project (#166)

changes/185.bugfix, taiga/models/models.py, tests/test_user_stories.py
Add swimlane to user story allowed_params
This should fix #185
=> Add swimlane to user story allowed_params

changes/196.bugfix, taiga/models/models.py, tests/test_issues.py, tox.ini
Add missing due_date to Issue allowed_params
Fix #196
=> Add missing due_date to Issue allowed_params
